apiVersion: v1
kind: LimitRange
metadata:
  name: default
spec:
  limits:
  - default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 500Mi
    max:
      cpu: 4
      memory: 8Gi
    type: Container
